# Generated by Django 4.2.9 on 2026-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Contrato'),
        ),
    ]
