# Generated by Django 4.2.9 on 2026-02-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='franqueado',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'FRANCHISEE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
