# Generated by Django 4.2.9 on 2026-02-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_playlist_franqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoExibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do agendamento', max_length=200)),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de dias da semana: 0=Seg, 1=Ter, 2=Qua, 3=Qui, 4=Sex, 5=Sáb, 6=Dom')),
                ('hora_inicio', models.TimeField(help_text='Hora de início da exibição')),
                ('hora_fim', models.TimeField(help_text='Hora de término da exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.dispositivotv')),
            ],
            options={
                'verbose_name': 'Agendamento de Exibição',
                'verbose_name_plural': 'Agendamentos de Exibição',
                'ordering': ['dispositivo', 'hora_inicio'],
            },
        ),
    ]
