# Generated by Django 4.2.9 on 2026-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agendamentoexibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação'), ('COMERCIO', 'Comércio'), ('SERVICOS', 'Serviços'), ('INDUSTRIA', 'Indústria'), ('TECNOLOGIA', 'Tecnologia'), ('CONSTRUCAO', 'Construção'), ('AUTOMOTIVO', 'Automotivo'), ('MODA', 'Moda e Beleza'), ('ENTRETENIMENTO', 'Entretenimento'), ('FINANCEIRO', 'Financeiro'), ('IMOBILIARIO', 'Imobiliário'), ('AGRONEGOCIO', 'Agronegócio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, verbose_name='Segmento'),
        ),
    ]
