# Generated by Django 4.2.9 on 2026-02-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_segmento_alter_cliente_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivotv',
            name='publico_estimado_mes',
            field=models.IntegerField(default=0, help_text='Estimativa de pessoas que visualizarão os anúncios por mês'),
        ),
    ]
