# Generated by Django 4.2.9 on 2026-02-08 00:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dispositivotv_publico_estimado_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(help_text='Ex: 1.0.0, 1.2.5', max_length=20, unique=True)),
                ('arquivo_apk', models.FileField(help_text='Arquivo APK do aplicativo', upload_to='app_versions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])])),
                ('tamanho', models.BigIntegerField(editable=False, help_text='Tamanho do arquivo em bytes')),
                ('notas_versao', models.TextField(blank=True, help_text='Descrição das mudanças nesta versão')),
                ('ativo', models.BooleanField(default=True, help_text='Versão disponível para download')),
                ('downloads', models.IntegerField(default=0, editable=False, help_text='Número de downloads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão do App',
                'verbose_name_plural': 'Versões do App',
                'ordering': ['-created_at'],
            },
        ),
    ]
