# Generated by Django 4.2.9 on 2026-02-19 00:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


def gen_unique_uuids(apps, schema_editor):
    """Gera UUIDs únicos para vídeos existentes"""
    Video = apps.get_model('core', 'Video')
    for video in Video.objects.all():
        video.qrcode_tracking_code = uuid.uuid4()
        video.save(update_fields=['qrcode_tracking_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='qrcode_descricao',
            field=models.CharField(blank=True, help_text='Texto exibido junto ao QR Code (ex: "Resgate seu desconto!", "Acesse nosso site")', max_length=100, null=True, verbose_name='Descrição do QR Code'),
        ),
        # Passo 1: Adicionar campo sem unique
        migrations.AddField(
            model_name='video',
            name='qrcode_tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único para rastrear acessos via QR Code', verbose_name='Código de rastreamento'),
        ),
        # Passo 2: Gerar UUIDs únicos para registros existentes
        migrations.RunPython(gen_unique_uuids, migrations.RunPython.noop),
        # Passo 3: Agora adicionar constraint unique
        migrations.AlterField(
            model_name='video',
            name='qrcode_tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único para rastrear acessos via QR Code', unique=True, verbose_name='Código de rastreamento'),
        ),
        migrations.AddField(
            model_name='video',
            name='qrcode_url_destino',
            field=models.URLField(blank=True, help_text='Link para onde o QR Code redirecionará (ex: site do cliente, Instagram, promoção)', max_length=500, null=True, verbose_name='URL de destino do QR Code'),
        ),
        migrations.CreateModel(
            name='QRCodeClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(db_index=True, help_text='Código de rastreamento do vídeo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_clicks', to='core.video')),
            ],
            options={
                'verbose_name': 'Clique QR Code',
                'verbose_name_plural': 'Cliques QR Code',
                'ordering': ['-created_at'],
            },
        ),
    ]
