# Generated by Django 4.2.9 on 2026-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_video_qrcode_descricao_video_qrcode_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivotv',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
