# Generated by Django 4.2.9 on 2026-02-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dispositivotv_ativo_alter_playlist_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='texto_tarja',
            field=models.CharField(blank=True, help_text='Texto exibido em tarja na parte inferior da tela durante o vídeo (estilo CNN). Ex: "Faça um storie com #media123 e ganhe um desconto!"', max_length=300, null=True, verbose_name='Texto da Tarja Inferior'),
        ),
    ]
