# Generated by Django 4.2.9 on 2026-02-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_video_texto_tarja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_max_requests_dia', models.IntegerField(default=100, help_text='Máximo de requisições/dia para API de previsão do tempo (Open-Meteo, grátis)')),
                ('weather_requests_hoje', models.IntegerField(default=0)),
                ('weather_ultimo_reset', models.DateField(auto_now_add=True)),
                ('cotacoes_max_requests_dia', models.IntegerField(default=100, help_text='Máximo de requisições/dia para API de cotações (AwesomeAPI, grátis)')),
                ('cotacoes_requests_hoje', models.IntegerField(default=0)),
                ('cotacoes_ultimo_reset', models.DateField(auto_now_add=True)),
                ('noticias_api_key', models.CharField(blank=True, help_text='Chave da API NewsAPI.org (grátis até 100 req/dia)', max_length=100, null=True)),
                ('noticias_max_requests_dia', models.IntegerField(default=50, help_text='Máximo de requisições/dia para API de notícias')),
                ('noticias_requests_hoje', models.IntegerField(default=0)),
                ('noticias_ultimo_reset', models.DateField(auto_now_add=True)),
                ('cache_weather_minutos', models.IntegerField(default=30, help_text='Tempo de cache para previsão do tempo (minutos)')),
                ('cache_cotacoes_minutos', models.IntegerField(default=15, help_text='Tempo de cache para cotações (minutos)')),
                ('cache_noticias_minutos', models.IntegerField(default=60, help_text='Tempo de cache para notícias (minutos)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de API',
                'verbose_name_plural': 'Configurações de API',
            },
        ),
        migrations.CreateModel(
            name='ConteudoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome de exibição do conteúdo', max_length=200)),
                ('tipo', models.CharField(choices=[('PREVISAO_TEMPO', 'Previsão do Tempo'), ('COTACOES', 'Cotações (Moedas, Cripto, Commodities)'), ('NOTICIAS', 'Notícias')], db_index=True, max_length=20)),
                ('duracao_segundos', models.IntegerField(default=15, help_text='Tempo de exibição na tela (segundos)')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteúdo Corporativo',
                'verbose_name_plural': 'Conteúdos Corporativos',
                'ordering': ['tipo', 'titulo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='municipio',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude do município (ex: -23.550520)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude do município (ex: -46.633308)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='repeticoes',
            field=models.IntegerField(default=1, help_text='Quantas vezes o item será exibido'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='core.video'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='conteudo_corporativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='core.conteudocorporativo'),
        ),
    ]
