# Generated by Django 4.2.9 on 2026-02-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_conteudo_corporativo_e_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentoexibicao',
            name='playlist',
            field=models.ForeignKey(blank=True, help_text='Playlist a ser exibida neste horário. Se vazio, usa a playlist padrão do dispositivo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.playlist'),
        ),
        migrations.AddField(
            model_name='agendamentoexibicao',
            name='prioridade',
            field=models.IntegerField(default=0, help_text='Prioridade do agendamento (maior = maior prioridade). Usado para resolver conflitos.'),
        ),
        migrations.CreateModel(
            name='AgendamentoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(help_text='Data/hora em que o vídeo começa a ser exibido')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data/hora em que o vídeo deixa de ser exibido (vazio = sem término)', null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Posição na playlist durante o período agendado')),
                ('repeticoes', models.IntegerField(default=1, help_text='Quantas vezes o vídeo é repetido por ciclo da playlist')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(help_text='Playlist onde o vídeo será exibido', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_video', to='core.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.video')),
            ],
            options={
                'verbose_name': 'Agendamento de Vídeo',
                'verbose_name_plural': 'Agendamentos de Vídeos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
