# Generated by Django 4.2.9 on 2026-02-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agendamento_playlist_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentoexibicao',
            options={'ordering': ['dispositivo', '-prioridade', 'hora_inicio'], 'verbose_name': 'Playlist Vinculada', 'verbose_name_plural': 'Playlists Vinculadas'},
        ),
        migrations.AddField(
            model_name='video',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='O vídeo deixa de aparecer nas TVs após esta data/hora (vazio = sem expiração)', null=True, verbose_name='Data de expiração'),
        ),
        migrations.AddField(
            model_name='video',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, help_text='Quando status=Agendado, o vídeo só aparece nas TVs a partir desta data/hora', null=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='agendamentoexibicao',
            name='dias_semana',
            field=models.JSONField(default=list, help_text='Dias da semana: 0=Seg..6=Dom. Vazio = todos os dias.'),
        ),
        migrations.AlterField(
            model_name='agendamentoexibicao',
            name='hora_fim',
            field=models.TimeField(blank=True, help_text='Hora de término (vazio = 24h)', null=True),
        ),
        migrations.AlterField(
            model_name='agendamentoexibicao',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de início (vazio = 24h)', null=True),
        ),
        migrations.AlterField(
            model_name='agendamentoexibicao',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome descritivo (opcional — gerado automaticamente se vazio)', max_length=200),
        ),
        migrations.AlterField(
            model_name='agendamentoexibicao',
            name='playlist',
            field=models.ForeignKey(help_text='Playlist a ser exibida neste dispositivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.playlist'),
        ),
        migrations.AlterField(
            model_name='agendamentoexibicao',
            name='prioridade',
            field=models.IntegerField(default=0, help_text='Prioridade (maior = maior prioridade). Usado para resolver conflitos.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('SCHEDULED', 'Agendado')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='AgendamentoVideo',
        ),
    ]
