# Generated by Django 4.2.9 on 2026-02-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_agendamentoexibicao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivotv',
            name='dias_funcionamento',
            field=models.JSONField(blank=True, default=list, help_text='Dias da semana que a TV funciona: 0=Seg..6=Dom. Vazio = todos.'),
        ),
        migrations.AddField(
            model_name='dispositivotv',
            name='hora_desligar',
            field=models.TimeField(blank=True, help_text='Hora que a TV desliga (ex: 17:00). Vazio = 24h.', null=True),
        ),
        migrations.AddField(
            model_name='dispositivotv',
            name='hora_ligar',
            field=models.TimeField(blank=True, help_text='Hora que a TV liga (ex: 08:00). Vazio = 24h.', null=True),
        ),
    ]
