# Generated by Django 4.2.9 on 2026-02-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dispositivotv_dias_funcionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivotv',
            name='dias_funcionamento',
        ),
        migrations.RemoveField(
            model_name='dispositivotv',
            name='hora_desligar',
        ),
        migrations.RemoveField(
            model_name='dispositivotv',
            name='hora_ligar',
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome descritivo (ex: Horário Comercial, Sábado)', max_length=200)),
                ('dias_semana', models.JSONField(default=list, help_text='Dias da semana: 0=Seg..6=Dom. Vazio = todos os dias.')),
                ('hora_inicio', models.TimeField(help_text='Hora que a TV liga')),
                ('hora_fim', models.TimeField(help_text='Hora que a TV desliga')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_funcionamento', to='core.dispositivotv')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['dispositivo', 'hora_inicio'],
            },
        ),
    ]
