# Generated by Django 4.2.9 on 2026-02-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_dispositivotv_dias_funcionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudocorporativo',
            name='design_altura',
            field=models.IntegerField(default=1080, help_text='Altura do design em pixels'),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='design_json',
            field=models.JSONField(blank=True, help_text='JSON do canvas Fabric.js com todos os elementos do design', null=True),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='design_largura',
            field=models.IntegerField(default=1920, help_text='Largura do design em pixels'),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='design_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail PNG gerada pelo editor', null=True, upload_to='designs/thumbnails/'),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Se marcado, aparece na galeria de modelos para reutilização'),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='template_categoria',
            field=models.CharField(blank=True, default='', help_text='Categoria do template (ex: Promoção, Institucional, Menu...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='conteudocorporativo',
            name='tipo',
            field=models.CharField(choices=[('PREVISAO_TEMPO', 'Previsão do Tempo'), ('COTACOES', 'Cotações (Moedas, Cripto, Commodities)'), ('NOTICIAS', 'Notícias'), ('DESIGN', 'Design Personalizado')], db_index=True, max_length=20),
        ),
    ]
