# Generated by Django 4.2.9 on 2026-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_design_editor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudocorporativo',
            name='cotacoes_commodities',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos de commodities para exibir (ex: ["gold", "oil"])'),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='cotacoes_cripto',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos de criptomoedas para exibir (ex: ["BTC", "ETH"])'),
        ),
        migrations.AddField(
            model_name='conteudocorporativo',
            name='cotacoes_moedas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos de moedas para exibir (ex: ["USD", "EUR", "GBP"])'),
        ),
    ]
