# Generated by Django 4.2.9 on 2026-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_logexibicaowebview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='orientacao',
            field=models.CharField(choices=[('HORIZONTAL', 'Horizontal (16:9 — Paisagem)'), ('VERTICAL', 'Vertical (9:16 — Retrato)')], default='HORIZONTAL', help_text='Horizontal (16:9) para vídeos gravados em paisagem; Vertical (9:16) para vídeos gravados em retrato (ex: iPhone na vertical)', max_length=10, verbose_name='Orientação'),
        ),
    ]
