# Generated by Django 4.2.9 on 2026-03-15 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_conteudocorporativo_franqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('tipo', models.CharField(choices=[('CUPOM', 'Resgate de Cupom de Desconto')], default='CUPOM', max_length=30, verbose_name='Tipo de Campanha')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada')], default='RASCUNHO', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da URL pública desta campanha.', unique=True)),
                ('data_fim', models.DateTimeField(blank=True, help_text='Deixe em branco para campanha sem prazo definido.', null=True, verbose_name='Data/Hora de Encerramento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('franqueado', models.ForeignKey(limit_choices_to={'role': 'FRANCHISEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to=settings.AUTH_USER_MODEL, verbose_name='Franqueado')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='conteudocorporativo',
            name='franqueado',
            field=models.ForeignKey(blank=True, help_text='Franqueado dono deste conteúdo. Nulo = pertence ao owner. Templates (is_template=True) são visíveis a todos.', limit_choices_to={'role': 'FRANCHISEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos_corporativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampanhaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=400)),
                ('codigo_cupom', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Lead de Campanha',
                'verbose_name_plural': 'Leads de Campanha',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaCupomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_codigo', models.CharField(choices=[('SEM_LEAD', 'Sem captura de dados — exibir código direto'), ('CODIGO_UNICO', 'Código único para todos'), ('CODIGO_POR_CLIENTE', 'Código individual por cliente (gerado na hora)')], default='CODIGO_UNICO', max_length=25, verbose_name='Modo de Código')),
                ('codigo_unico', models.CharField(blank=True, help_text='Código que será exibido a todos os usuários (modo Código Único).', max_length=100, verbose_name='Código do Cupom')),
                ('prefixo_codigo', models.CharField(blank=True, help_text='Prefixo para os códigos individuais gerados. Ex: "PROMO" → PROMO-A1B2.', max_length=20, verbose_name='Prefixo dos Códigos')),
                ('capturar_nome', models.BooleanField(default=False, verbose_name='Capturar Nome')),
                ('capturar_cpf', models.BooleanField(default=False, verbose_name='Capturar CPF')),
                ('capturar_telefone', models.BooleanField(default=False, verbose_name='Capturar Telefone')),
                ('capturar_endereco', models.BooleanField(default=False, verbose_name='Capturar Endereço')),
                ('titulo_pagina', models.CharField(blank=True, help_text='Deixe em branco para usar o nome da campanha.', max_length=200, verbose_name='Título da Página')),
                ('descricao_pagina', models.TextField(blank=True, help_text='Texto exibido na landing page antes do formulário.', verbose_name='Descrição / Instrução')),
                ('cor_primaria', models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor Principal (hex)')),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_cupom', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Configuração de Cupom',
            },
        ),
    ]
