# Generated by Django 4.2.9 on 2026-03-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_campanha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='tipo',
            field=models.CharField(choices=[('CUPOM', 'Resgate de Cupom de Desconto'), ('ROLETA', 'Roleta de Prêmios')], default='CUPOM', max_length=30, verbose_name='Tipo de Campanha'),
        ),
        migrations.CreateModel(
            name='CampanhaRoletaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Prêmio')),
                ('descricao', models.CharField(blank=True, max_length=400, verbose_name='Descrição')),
                ('codigo_resgate', models.CharField(blank=True, help_text='Código ou instrução entregue ao ganhador (opcional).', max_length=100, verbose_name='Código de Resgate')),
                ('peso', models.PositiveIntegerField(default=10, help_text='Quanto maior o peso, mais chance de sair.', verbose_name='Peso de Probabilidade')),
                ('quantidade_maxima', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para ilimitado.', null=True, verbose_name='Qtd. Máxima de Ganhadores')),
                ('cor', models.CharField(default='#f4a261', max_length=7, verbose_name='Cor do Segmento')),
                ('emoji', models.CharField(blank=True, default='🎁', max_length=10, verbose_name='Emoji')),
                ('eh_perdedor', models.BooleanField(default=False, help_text='Se marcado, o participante não ganha prêmio ao cair aqui.', verbose_name='É Segmento Perdedor?')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem na roleta')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_roleta', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Prêmio da Roleta',
                'verbose_name_plural': 'Prêmios da Roleta',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaRoletaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_jogadas_por_ip_por_dia', models.PositiveIntegerField(default=1, help_text='0 = ilimitado por dia', verbose_name='Máx. jogadas por IP por dia')),
                ('max_jogadas_total_por_ip', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para sem limite absoluto.', null=True, verbose_name='Máx. jogadas total por IP')),
                ('capturar_nome', models.BooleanField(default=True, verbose_name='Capturar Nome')),
                ('capturar_cpf', models.BooleanField(default=False, verbose_name='Capturar CPF')),
                ('capturar_telefone', models.BooleanField(default=True, verbose_name='Capturar Telefone')),
                ('capturar_endereco', models.BooleanField(default=False, verbose_name='Capturar Endereço')),
                ('titulo_pagina', models.CharField(blank=True, max_length=200, verbose_name='Título da Página')),
                ('descricao_pagina', models.TextField(blank=True, verbose_name='Instruções para o participante')),
                ('cor_primaria', models.CharField(default='#e63946', max_length=7, verbose_name='Cor Principal')),
                ('texto_botao_girar', models.CharField(default='GIRAR!', max_length=50, verbose_name='Texto do botão de girar')),
                ('texto_sem_premio', models.CharField(default='Não foi desta vez! Tente novamente.', help_text='Exibida quando o participante cai num segmento perdedor.', max_length=150, verbose_name='Mensagem de consolação')),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_roleta', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Config. Roleta',
            },
        ),
        migrations.CreateModel(
            name='CampanhaJogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ganhou', models.BooleanField(default=False)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=400)),
                ('lead_salvo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadas', to='core.campanha')),
                ('premio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadas', to='core.campanharoletapremio')),
            ],
            options={
                'verbose_name': 'Jogada',
                'verbose_name_plural': 'Jogadas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
