# Generated by Django 4.2.9 on 2026-03-18 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_roleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='tipo',
            field=models.CharField(choices=[('CUPOM', 'Resgate de Cupom de Desconto'), ('ROLETA', 'Roleta de Prêmios'), ('CARTA', 'Virar a Carta')], default='CUPOM', max_length=30, verbose_name='Tipo de Campanha'),
        ),
        migrations.CreateModel(
            name='CampanhaCartaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_jogadas_por_ip_por_dia', models.PositiveIntegerField(default=1, help_text='0 = ilimitado por dia', verbose_name='Máx. jogadas por IP por dia')),
                ('max_jogadas_total_por_ip', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para sem limite absoluto.', null=True, verbose_name='Máx. jogadas total por IP')),
                ('capturar_nome', models.BooleanField(default=True, verbose_name='Capturar Nome')),
                ('capturar_cpf', models.BooleanField(default=False, verbose_name='Capturar CPF')),
                ('capturar_telefone', models.BooleanField(default=True, verbose_name='Capturar Telefone')),
                ('capturar_endereco', models.BooleanField(default=False, verbose_name='Capturar Endereço')),
                ('titulo_pagina', models.CharField(blank=True, max_length=200, verbose_name='Título da Página')),
                ('descricao_pagina', models.TextField(blank=True, verbose_name='Instruções')),
                ('cor_primaria', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Cor de Fundo da Página')),
                ('cor_verso_carta', models.CharField(default='#16213e', max_length=7, verbose_name='Cor do Verso da Carta')),
                ('cor_frente_carta', models.CharField(default='#e63946', max_length=7, verbose_name='Cor da Frente da Carta')),
                ('texto_verso_carta', models.CharField(default='Vire a carta!', max_length=100, verbose_name='Texto no verso da carta')),
                ('texto_botao_virar', models.CharField(default='Virar a Carta!', max_length=50, verbose_name='Texto do botão')),
                ('texto_sem_premio', models.CharField(default='Não foi desta vez! Tente novamente.', max_length=150, verbose_name='Mensagem de consolação')),
                ('logo', models.ImageField(blank=True, help_text='Opcional. Se não informado, exibe padrão de cartas.', null=True, upload_to='campanhas/logos/', verbose_name='Logo da empresa (verso da carta)')),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_carta', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Config. Carta',
            },
        ),
    ]
