# Generated by Django 4.2.9 on 2026-03-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_carta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='tipo',
            field=models.CharField(choices=[('CUPOM', 'Resgate de Cupom de Desconto'), ('ROLETA', 'Roleta de Prêmios'), ('CARTA', 'Virar a Carta'), ('ALERTA', 'Alerta de Preços')], default='CUPOM', max_length=30, verbose_name='Tipo de Campanha'),
        ),
        migrations.CreateModel(
            name='CampanhaAlertaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('respostas', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_alerta', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Lead de Alerta',
                'verbose_name_plural': 'Leads de Alerta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaAlertaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pagina', models.CharField(blank=True, help_text='Deixe em branco para usar o nome da campanha.', max_length=200, verbose_name='Título da Página Pública')),
                ('subtitulo_pagina', models.CharField(blank=True, help_text='Frase que motiva o visitante a preencher o formulário.', max_length=300, verbose_name='Subtítulo / Texto de Conversão')),
                ('descricao_pagina', models.TextField(blank=True, help_text='Texto exibido abaixo do título antes do formulário.', verbose_name='Descrição / Instruções')),
                ('mensagem_sucesso', models.CharField(default='Seu alerta foi cadastrado! Entraremos em contato assim que encontrarmos o que você procura.', max_length=400, verbose_name='Mensagem de Sucesso')),
                ('whatsapp_contato', models.CharField(blank=True, help_text='Número no formato 5511999990000. Exibido após o envio.', max_length=20, verbose_name='WhatsApp para Contato')),
                ('cor_primaria', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Cor Principal (hex)')),
                ('cor_destaque', models.CharField(default='#e63946', max_length=7, verbose_name='Cor de Destaque (hex)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='campanhas/logos/', verbose_name='Logo da empresa')),
                ('capturar_nome', models.BooleanField(default=True, verbose_name='Capturar Nome')),
                ('capturar_telefone', models.BooleanField(default=True, verbose_name='Capturar Telefone')),
                ('capturar_email', models.BooleanField(default=False, verbose_name='Capturar E-mail')),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_alerta', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Config. Alerta de Preços',
            },
        ),
        migrations.CreateModel(
            name='CampanhaAlertaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto livre'), ('NUMERO', 'Número inteiro'), ('MOEDA', 'Valor monetário (R$)'), ('SELECT', 'Seleção única (lista)'), ('MULTISELECT', 'Seleção múltipla'), ('BOOLEAN', 'Pergunta Sim/Não')], default='TEXTO', max_length=15)),
                ('rotulo', models.CharField(help_text='Pergunta exibida ao visitante. Ex: “Qual tipo de imóvel você procura?”', max_length=200, verbose_name='Rótulo do Campo')),
                ('placeholder', models.CharField(blank=True, help_text='Texto de dica dentro do campo (opcional).', max_length=200, verbose_name='Placeholder / Dica')),
                ('opcoes', models.TextField(blank=True, help_text='Para tipo SELECT ou MULTISELECT: coloque uma opção por linha.', verbose_name='Opções (uma por linha)')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_alerta', to='core.campanha')),
            ],
            options={
                'verbose_name': 'Campo do Alerta',
                'verbose_name_plural': 'Campos do Alerta',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
