# Generated by Django 4.2.9 on 2026-03-31 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alerta_precos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanhaalertaconfig',
            options={'verbose_name': 'Config. Alerta Inteligente'},
        ),
        migrations.AddField(
            model_name='dispositivotv',
            name='franqueado',
            field=models.ForeignKey(blank=True, help_text='Franqueado responsável por este dispositivo. Permite transferir a gestão da TV ao franqueado sem alterar o município.', limit_choices_to={'role': 'FRANCHISEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_franqueado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='tipo',
            field=models.CharField(choices=[('CUPOM', 'Resgate de Cupom de Desconto'), ('ROLETA', 'Roleta de Prêmios'), ('CARTA', 'Virar a Carta'), ('ALERTA', 'Alerta Inteligente')], default='CUPOM', max_length=30, verbose_name='Tipo de Campanha'),
        ),
    ]
