# Generated by Django 4.2.9 on 2026-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_dispositivotv_franqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivotv',
            name='alerta_desconexao_enviado',
            field=models.BooleanField(default=False, help_text='True quando o alerta de desconexão já foi enviado e o dispositivo continua offline.'),
        ),
    ]
