# Generated by Django 4.2.9 on 2026-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_dispositivotv_alerta_desconexao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('segmento', models.CharField(blank=True, choices=[('barbearia_salao', 'Barbearia / Salão'), ('restaurante', 'Restaurante / Lanchonete'), ('loja_roupa', 'Loja de Roupa / Calçados'), ('oficina', 'Oficina Mecânica'), ('academia', 'Academia / Studio'), ('farmacia_otica', 'Farmácia / Ótica'), ('petshop', 'Petshop'), ('clinica', 'Clínica / Consultório'), ('supermercado', 'Supermercado / Mercearia'), ('comercio_geral', 'Comércio em Geral'), ('outro', 'Outro')], max_length=40, verbose_name='Segmento do negócio')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead da Landing Page',
                'verbose_name_plural': 'Leads da Landing Page',
                'ordering': ['-criado_em'],
            },
        ),
    ]
