# Generated by Django 4.2.9 on 2026-04-08 22:39

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sorteio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Assistente do Café Silva', max_length=100, verbose_name='Nome do Agente')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente — define a URL pública', max_length=120, unique=True)),
                ('descricao_curta', models.CharField(blank=True, help_text='Aparece abaixo do nome no chat', max_length=200, verbose_name='Tagline')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.agente_avatar_upload, verbose_name='Avatar / Foto do Agente')),
                ('nome_empresa', models.CharField(blank=True, help_text='Contexto para o agente saber onde trabalha', max_length=200, verbose_name='Nome da Empresa')),
                ('modelo_ia', models.CharField(choices=[('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet (Anthropic)'), ('claude-3-haiku-20240307', 'Claude 3 Haiku (Anthropic)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)')], default='gpt-4o-mini', max_length=60, verbose_name='Modelo de IA')),
                ('api_key', models.CharField(help_text='Chave secreta do provedor (OpenAI, Anthropic, Google…)', max_length=200, verbose_name='Chave de API')),
                ('temperatura', models.FloatField(default=0.7, help_text='0 = respostas determinísticas | 1 = mais criativas', verbose_name='Temperatura (criatividade)')),
                ('max_tokens', models.PositiveIntegerField(default=500, verbose_name='Máx. tokens por resposta')),
                ('prompt_sistema', models.TextField(help_text='Descreva quem é o agente, o que pode responder, o tom de voz, informações sobre a loja…', verbose_name='Prompt de Sistema (treinamento)')),
                ('restricoes', models.TextField(blank=True, help_text='O que o agente NÃO deve responder (ex: política, concorrentes)', verbose_name='Restrições')),
                ('mensagem_boas_vindas', models.TextField(default='Olá! Como posso te ajudar hoje? 😊', verbose_name='Mensagem de Boas-vindas')),
                ('cor_primaria', models.CharField(default='#6366f1', max_length=7, verbose_name='Cor Principal')),
                ('placeholder_input', models.CharField(default='Digite sua mensagem…', max_length=100, verbose_name='Placeholder do campo de mensagem')),
                ('coleta_contato', models.BooleanField(default=False, verbose_name='Coletar dados antes do chat')),
                ('coleta_nome', models.BooleanField(default=True, verbose_name='Pedir nome')),
                ('coleta_telefone', models.BooleanField(default=False, verbose_name='Pedir telefone')),
                ('coleta_email', models.BooleanField(default=False, verbose_name='Pedir e-mail')),
                ('mensagem_coleta', models.CharField(blank=True, default='Para continuar, preencha seus dados:', max_length=200, verbose_name='Mensagem antes da coleta')),
                ('limite_mensagens', models.PositiveIntegerField(default=0, help_text='0 = sem limite', verbose_name='Limite de mensagens por sessão')),
                ('whatsapp_escalada', models.CharField(blank=True, help_text='Número com DDI ex: 5511999999999 — exibe botão de escalada', max_length=30, verbose_name='WhatsApp de suporte')),
                ('mensagem_escalada', models.CharField(blank=True, default='Preciso falar com um atendente', max_length=200, verbose_name='Texto do botão de escalada')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('franqueado', models.ForeignKey(limit_choices_to={'role': 'FRANCHISEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='agentes_ia', to=settings.AUTH_USER_MODEL, verbose_name='Franqueado')),
            ],
            options={
                'verbose_name': 'Agente de IA',
                'verbose_name_plural': 'Agentes de IA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AgenteIAConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_visitante', models.CharField(blank=True, max_length=100)),
                ('telefone_visitante', models.CharField(blank=True, max_length=30)),
                ('email_visitante', models.EmailField(blank=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_mensagens', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='core.agenteia')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='campanhaparticipantesorteio',
            name='ativo_sorteio',
            field=models.BooleanField(default=True, help_text='Desmarque para excluir este participante do sorteio (duplicatas, etc.).', verbose_name='Participar do Sorteio'),
        ),
        migrations.AlterField(
            model_name='campanhasorteioconfig',
            name='bloquear_duplicados_cpf',
            field=models.BooleanField(default=True, help_text='Impede que o mesmo CPF se inscreva mais de uma vez.', verbose_name='Bloquear CPF duplicado'),
        ),
        migrations.AlterField(
            model_name='campanhasorteioconfig',
            name='bloquear_duplicados_ip',
            field=models.BooleanField(default=False, help_text='Impede que o mesmo IP se inscreva mais de uma vez.', verbose_name='Bloquear IP duplicado'),
        ),
        migrations.AlterField(
            model_name='campanhasorteioconfig',
            name='data_sorteio',
            field=models.DateTimeField(blank=True, help_text='Opcional. Exibida na página para criar urgência.', null=True, verbose_name='Data/Hora do Sorteio'),
        ),
        migrations.AlterField(
            model_name='campanhasorteioconfig',
            name='descricao_pagina',
            field=models.TextField(blank=True, help_text='Texto motivacional exibido antes do formulário de inscrição.', verbose_name='Descrição / Instruções'),
        ),
        migrations.AlterField(
            model_name='campanhasorteioconfig',
            name='foto_item',
            field=models.ImageField(blank=True, help_text='Opcional. Imagem do prêmio exibida na página de inscrição.', null=True, upload_to='campanhas/sorteio/', verbose_name='Foto do Item Sorteado'),
        ),
        migrations.AlterField(
            model_name='campanhasorteioconfig',
            name='titulo_pagina',
            field=models.CharField(blank=True, help_text='Deixe em branco para usar o nome da campanha.', max_length=200, verbose_name='Título da Página Pública'),
        ),
        migrations.CreateModel(
            name='AgenteIAMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Agente')], max_length=10)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.agenteiaconversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criado_em'],
            },
        ),
    ]
