# Generated by Django 4.2.9 on 2026-04-10 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_agenteia_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteiaconversa',
            name='assumido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenteiaconversa',
            name='assumido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_assumidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenteiaconversa',
            name='modo',
            field=models.CharField(choices=[('ia', 'IA'), ('humano', 'Humano')], default='ia', max_length=10),
        ),
        migrations.AddField(
            model_name='agenteiaconversa',
            name='qualificacao',
            field=models.CharField(choices=[('hot', 'Quente'), ('warm', 'Morno'), ('cold', 'Frio'), ('none', 'Indefinido')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='agenteiaconversa',
            name='qualificacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenteiaconversa',
            name='qualificacao_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenteia',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente — uso interno', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='agenteiamensagem',
            name='role',
            field=models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Agente'), ('human', 'Humano')], max_length=10),
        ),
    ]
