# Generated by Django 4.2.9 on 2026-04-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_agenteia_conversa_takeover_qualificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteia',
            name='habilitar_qualificacao',
            field=models.BooleanField(default=False, help_text='A IA analisa silenciosamente a conversa e classifica o lead como Quente/Morno/Frio.', verbose_name='Classificar leads automaticamente'),
        ),
        migrations.CreateModel(
            name='AgenteIAAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(help_text='Identificador curto sem espaços (usado internamente pela IA). Ex: verificar_disponibilidade', max_length=60)),
                ('descricao', models.TextField(help_text='Explique o que esta ação faz e quando a IA deve usá-la. Ex: "Verifica salas disponíveis em uma data e com certa capacidade."')),
                ('url', models.CharField(help_text='URL do endpoint. Suporta {placeholders} preenchidos com parâmetros. Ex: https://api.exemplo.com/salas/{data}', max_length=500)),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('headers_json', models.TextField(blank=True, default='{}', help_text='JSON com os headers da requisição. Ex: {"Authorization": "Bearer TOKEN", "Content-Type": "application/json"}', verbose_name='Headers (JSON)')),
                ('corpo_template', models.TextField(blank=True, help_text='Template JSON para o corpo do POST/PUT. Use {nome_param} para valores dinâmicos. Ex: {"data": "{data}", "capacidade": "{capacidade}"}', verbose_name='Corpo da requisição (template JSON)')),
                ('parametros_json', models.TextField(blank=True, default='[]', help_text='Lista JSON dos parâmetros que a IA deve coletar. Ex: [{"nome": "data", "tipo": "string", "descricao": "Data no formato YYYY-MM-DD", "obrigatorio": true}]', verbose_name='Parâmetros (JSON)')),
                ('exibir_botao', models.BooleanField(default=False, help_text='Exibe um botão de atalho no chat para iniciar esta ação diretamente')),
                ('texto_botao', models.CharField(blank=True, help_text='Texto do botão exibido no chat. Ex: "Ver salas disponíveis"', max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='core.agenteia')),
            ],
            options={
                'verbose_name': 'Ação do Agente',
                'verbose_name_plural': 'Ações do Agente',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
