# Generated by Django 4.2.9 on 2026-04-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_agenteia_acoes_qualificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteiaacao',
            name='tipo',
            field=models.CharField(choices=[('http', 'Chamada HTTP (API externa)'), ('capturar', 'Capturar pedido/dados')], default='http', help_text='"Chamada HTTP" faz uma requisição a uma API externa. "Capturar pedido/dados" salva os dados no banco e opcionalmente dispara um webhook.', max_length=20),
        ),
        migrations.AlterField(
            model_name='agenteiaacao',
            name='url',
            field=models.CharField(blank=True, help_text='URL do endpoint. Suporta {placeholders} preenchidos com parâmetros. Para tipo "Capturar", é o webhook opcional que receberá os dados via POST.', max_length=500),
        ),
        migrations.CreateModel(
            name='AgenteIACaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(help_text='Payload JSON coletado pela IA (itens, quantidades, preços, obs, etc.)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('webhook_enviado', models.BooleanField(default=False)),
                ('webhook_resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acao', models.ForeignKey(blank=True, help_text='Ação que originou esta captura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas', to='core.agenteiaacao')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='core.agenteia')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='core.agenteiaconversa')),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
